version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: wynni-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: WYNNI
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: wynni-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wynni-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://postgres:123@postgres:5432/WYNNI?schema=public"
      PORT: 3001
      CORS_ORIGIN: "http://localhost:3000"
      JWT_SECRET: "wynni-production-jwt-super-secret-key-2026"
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: wynni-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:3001"
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:
